### ISSUE TITLE
import error using export-onnx-inference-onnxruntime.ipynb

### ISSUE THREAD

**Issue by hansoullee20** [zhiqwang/yolov5-rt-stack#247]
### 🐛 Describe the bug

Hello!! Thank you for your work!

I am trying to run export-onnx-inference-onnxruntime.ipynb notebook. When I run the following line I get an error:

import onnx

the error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/onnx.py", line 3, in <module>
    from onnx_tf.backend import prepare
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py", line 15, in <module>
    from onnx import defs
ImportError: cannot import name 'defs'```

how can i fix this issue? Ive tried to update the package with following:
pip install onnx --upgrade


### Versions

PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.25

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-87-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: 
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.5.5
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchmetrics==0.6.1
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

**Comment by zhiqwang** [comment]
Hi @hansoullee20 

Seems there' s a file "onnx.py" with the same name as `onnx` that causes some ambiguity in loading the module, can you change the name of this file to something like "onnx_test.py"?

**Comment by hansoullee20** [comment]
@zhiqwang thank you for such a fast reply! ineed that was the issue.
