### ISSUE TITLE
`detect.py` does not run if `tensorrt` is not installed 

### ISSUE THREAD

**Issue by mattpopovich** [zhiqwang/yolov5-rt-stack#281]
### 🐛 Describe the bug

I'm not sure if you _wanted_ `detect.py` to be able to run without `tensorrt` installed, but these lines:

https://github.com/zhiqwang/yolov5-rt-stack/blob/3485ea144fec7b2857d0d2e0d4ff329959e77027/yolort/runtime/y_tensorrt.py#L15-L18

make me think you did not want `tensorrt` to be required, so I'm raising this issue just in case you wanted to take a look at it. 

`trt` gets set to `None`and then `trt_logger = trt.Logger(trt.Logger.INFO)` fails because `trt` is a `NoneType` and has no attribute `Logger`:

```console
matt@linux: yolov5-rt-stack# python3 tools/detect.py --weights models/yolov5s-v6.0.pt --source bus.jpg 
No protocol specified
Command Line Args: Namespace(classes=None, conf_thres=0.25, device='', exist_ok=False, half=False, hide_conf=False, hide_labels=False, img_size=[640], iou_thres=0.45, line_thickness=3, max_det=1000, name='exp', nosave=False, project='./runs/detect', save_conf=False, save_crop=False, save_txt=False, source='bus.jpg', update=False, view_img=False, visualize=False, weights='models/yolov5s-v6.0.pt')
YOLOv5 🚀 v0.5.2-alpha-54-g3485ea1 torch 1.9.0a0+gitd69c22d CUDA:0 (GeForce GTX 1080, 8120MiB)

Loading models/yolov5s-v6.0.pt for TensorRT inference...
Traceback (most recent call last):
  File "tools/detect.py", line 248, in <module>
    cli_main()
  File "tools/detect.py", line 244, in cli_main
    run(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "tools/detect.py", line 105, in run
    engine = PredictorTRT(weights, device=device)
  File "/home/mpopovich/git/yolov5-rt-stack/yolort/runtime/y_tensorrt.py", line 65, in __init__
    self.engine = self._build_engine()
  File "/home/mpopovich/git/yolov5-rt-stack/yolort/runtime/y_tensorrt.py", line 71, in _build_engine
    trt_logger = trt.Logger(trt.Logger.INFO)
AttributeError: 'NoneType' object has no attribute 'Logger'
matt@linux: yolov5-rt-stack# python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt as trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorrt'
```

### Versions

<details><summary>Click to display Versions</summary>
<p>

```console
# python3 -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.9.0a0+gitd69c22d
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-92-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080

Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] pytorch-lightning==1.5.8
[pip3] torch==1.9.0a0+gitd69c22d
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.10.0a0+300a8a4
[conda] Could not collect

```
</p>
</details>

**Comment by zhiqwang** [comment]
Hi @mattpopovich ,

> I'm not sure if you wanted detect.py to be able to run without tensorrt installed

Currently, the `detect.py` is for TensorRT Python inferencing, so we need to install TensorRT first.

> make me think you did not want tensorrt to be required.

Yep, we don't want to make TensorRT as required. There are two reasons for these:

First, install TensorRT is a little tricky, and we hope user to install TensorRT manually, check the install guide of TensorRT <https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html>.
And there is a Python Wheel for running `detect.py` on Ubuntu 18.04+ and CentOS 7+ with Python versions 3.6 to 3.9 and CUDA 11.x
```
pip install -U nvidia-tensorrt --index-url https://pypi.ngc.nvidia.com  # install
```
Check more details at <https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-pip>.

Second, TensorRT only works at Nvidia GPU, if we set TensorRT to be required, most of the other functions will not be available, even if these codes do not rely on TensorRT.

**Comment by zhiqwang** [comment]
Hi @mattpopovich ,

We added a verification that TensorRT is installed in the initialization and installation instructions in #311 . As such I'm closing this ticket.

Thanks for reporting this issue to us!
