### ISSUE TITLE
Axis 3 has mismatched dimensions of 15 and 16 when running ONNX Runtime inference

### ISSUE THREAD

**Issue by hudfdfdf** [zhiqwang/yolov5-rt-stack#407]
I convert yolov5s.pt(6.0) to onnx success. But I have the following problem while ONNX Runtime

2022-05-21 17:12:03.380534968 [W:onnxruntime:, graph.cc:1074 Graph] Initializer 1582 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2022-05-21 17:12:03.380578928 [W:onnxruntime:, graph.cc:1074 Graph] Initializer 1591 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2022-05-21 17:12:03.380593136 [W:onnxruntime:, graph.cc:1074 Graph] Initializer 1592 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2022-05-21 17:12:03.380606114 [W:onnxruntime:, graph.cc:1074 Graph] Initializer 1594 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2022-05-21 17:12:03.380655769 [W:onnxruntime:, graph.cc:1074 Graph] Initializer 1578 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2022-05-21 17:12:03.680912424 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Concat node. Name:'Concat_289' Status Message: concat.cc:84 PrepareForCompute Non concat axis dimensions must match: Axis 3 has mismatched dimensions of 15 and 16
Traceback (most recent call last):
    predictions = y_runtime.predict("yolov5-rt-stack/test/assets/bus.jpg")
  File "yolov5-rt-stack/yolort/runtime/y_onnxruntime.py", line 117, in predict
    return self(images)
  File "yolov5-rt-stack/yolort/runtime/y_onnxruntime.py", line 101, in __call__
    predictions = self._runtime.run(output_names=None, input_feed=inputs)
  File "anaconda3/envs/torch18/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'Concat_289' Status Message: concat.cc:84 PrepareForCompute Non concat axis dimensions must match: Axis 3 has mismatched dimensions of 15 and 16

Do you have any good suggestion to solve this problem？thanks.

**Comment by zhiqwang** [comment]
Hi @hudfdfdf , Seems that there is a problem with the settings of image input shape, could you please post the codes to reproduce the issue?

**Comment by hudfdfdf** [comment]
> Hi @hudfdfdf , Seems that there is a problem with the settings of input image shapes, could you please share the codes to reproduce the issue?
convert codes: python tools/export_model.py --checkpoint_path yolov5s.pt --onnx_path yolov5s.onnx

ONNX Runtime codes:
from yolort.runtime import PredictorORT
engine_path = "yolov5s.onnx"
y_runtime = PredictorORT(engine_path, device="cuda")
predictions = y_runtime.predict("bus.jpg")

onnx model graph:
![yolov5s onnx](https://user-images.githubusercontent.com/40683720/169652754-88e6179b-bdb9-4f1f-a2ab-5168f649f154.svg)

**Comment by zhiqwang** [comment]
Thanks for the details codes, and what's the version of ONNX Runtime and yolort you are using now?

**Comment by hudfdfdf** [comment]
Package                            Version               Editable project location
---------------------------------- --------------------- ----------------------------
torch                              1.8.0
torchfile                          0.1.0
torchvision                        0.9.0
tornado                            5.0.2
onnx                               1.11.0
onnxoptimizer                      0.2.7
onnxruntime                        1.10.0

**Comment by hudfdfdf** [comment]
> Thanks for sharing the details codes, and what's the version of PyTorch, ONNX Runtime and yolort you are using now?

Package                            Version               Editable project location
---------------------------------- --------------------- ----------------------------
torch                              1.8.0
torchfile                          0.1.0
torchvision                        0.9.0
tornado                            5.0.2
onnx                               1.11.0
onnxoptimizer                      0.2.7
onnxruntime                        1.10.0

**Comment by hudfdfdf** [comment]
> Thanks for sharing the details codes, and what's the version of PyTorch, ONNX Runtime and yolort you are using now?

yolort                             0.7.0a0+006f3f6

**Comment by zhiqwang** [comment]
And yolov5s.pt is downloaded from https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s.pt or https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt ?

**Comment by zhiqwang** [comment]
Hi @hudfdfdf , Sorry here, I cann't reproduce this bug like you here, could you set the device to "cpu" and see what happened?

**Comment by hudfdfdf** [comment]
> input image shape

It is https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s6.pt .   The input  size should 1280. 
This is my fault. Thank you

**Comment by hudfdfdf** [comment]
> input image shape

It is https://github.com/ultralytics/yolov5/releases/download/v6.1/yolov5s6.pt .   The input  size should 1280. 
This is my fault. Thank you

**Comment by zhiqwang** [comment]
Hi @hudfdfdf , Congratulations and very glad to here you've resolved this problem.
BTW, Actually 640 will also be okay for `yolov5s6`, you need add one more arguments `--size_divisible 64` when exporting the ONNX models. See https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/onnxruntime#usage for more details.

**Comment by hudfdfdf** [comment]
> Hi @hudfdfdf , Congratulations and very glad to here you've resolved this problem.
> 
> BTW, Actually 640 will also be okay for `yolov5s6`, you need add one more arguments `--size_divisible 64` when exporting the ONNX models. See https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/onnxruntime#usage for more details.

OK, thanks for your reply and sharing quickly. Thank you very much.
