### ISSUE TITLE
I'm unable to convert yolov5 ultralytics to an engine or onnx file

### ISSUE THREAD

**Issue by rlewkowicz** [zhiqwang/yolov5-rt-stack#428]
### 🐛 Describe the bug

I'm well versed with yolov5 ultralytics. I've trained models, run inference etc. Now I want to deploy one of those models with tensorrt. 

I'm trying to use the export model tools, and it just doesn't do anything. It completes with a few warns and does no file output. My models were from the master branch, and not 6.0. Is that going to cause issues? I'm rebuilding the model against 6.0 in the interim. 

Then I tried the convert_yolov5_to_yolort.py. This is successful, but then I cannot export the model.

```
(p37) PS C:\Repos\screen\yolov5-rt-stack\tools> python .\export_model.py --checkpoint_path .\yolov5_darknet_pan_n_r60_custom.pt --include engine
Command Line Args: Namespace(batch_size=1, checkpoint_path='.\\yolov5_darknet_pan_n_r60_custom.pt', image_size=[640, 640], include=['engine'], nms_thresh=0.45, onnx_path=None, opset=11, score_thresh=0.25, simplify=False, size_divisible=32, skip_preprocess=False, trt_path=None, version='r6.0')
Traceback (most recent call last):
  File ".\export_model.py", line 193, in <module>
    cli_main()
  File ".\export_model.py", line 185, in cli_main
    input_sample=input_sample,
  File ".\export_model.py", line 137, in export_tensorrt
    workspace=workspace,
  File "C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\runtime\trt_helper.py", line 68, in export_tensorrt_engine
    yolo_gs = YOLOTRTGraphSurgeon(checkpoint_path, version=version, input_sample=input_sample)
  File "C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\relay\trt_graphsurgeon.py", line 63, in __init__
    model = YOLOTRTInference(checkpoint_path, version=version)
  File "C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\relay\trt_inference.py", line 32, in __init__
    model_info = load_from_ultralytics(checkpoint_path, version=version)
  File "C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\_checkpoint.py", line 33, in load_from_ultralytics
    checkpoint_yolov5 = load_yolov5_model(checkpoint_path)
  File "C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\v5\helper.py", line 71, in load_yolov5_model
    model = ckpt["ema" if ckpt.get("ema") else "model"].float().eval()
KeyError: 'model'
```

It's as if it's trying to double convert it. 

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: 13.0.0
CMake version: version 3.24.0-rc1
Libc version: N/A

Python version: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 512.95
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] numpydoc==1.2
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py37h2bbff1b_0
[conda] mkl_fft                   1.3.1            py37h277e83a_0
[conda] mkl_random                1.2.2            py37hf11a4ad_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  1.2                pyhd3eb1b0_0
[conda] pytorch                   1.11.0          py3.7_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0               py37_cu113    pytorch
```

**Comment by zhiqwang** [comment]
Hi @rlewkowicz could you post your original bug when exporting with export_model.py

**Comment by rlewkowicz** [comment]
Sure! @zhiqwang 

```
(p37) PS C:\Repos\screen\yolov5-rt-stack\tools> python .\export_model.py --checkpoint_path ..\..\yolov5\runs\train\exp9\weights\best.pt --include engine --trt_path "."
Command Line Args: Namespace(batch_size=1, checkpoint_path='..\\..\\yolov5\\runs\\train\\exp9\\weights\\best.pt', image_size=[640, 640], include=['engine'], nms_thresh=0.45, onnx_path=None, opset=11, score_thresh=0.25, simplify=False, size_divisible=32, skip_preprocess=False, trt_path='.', version='r6.0')
Loaded saved model from ..\..\yolov5\runs\train\exp9\weights\best.pt
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\anchor_utils.py:46: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchors = torch.as_tensor(self.anchor_grids, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\anchor_utils.py:47: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\relay\logits_decoder.py:45: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\box_head.py:337: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for head_output, grid, shift, stride in zip(head_outputs, grids, shifts, strides):
  ```
  I'll take a look at those docs

**Comment by zhiqwang** [comment]
Seems that these are warning here? I guess you can ignore it.

**Comment by zhiqwang** [comment]
And seems that we should input the file path to trt_path
```sh
python .\export_model.py --checkpoint_path ..\..\yolov5\runs\train\exp9\weights\best.pt --include engine --trt_path "model.engine"
```

**Comment by rlewkowicz** [comment]
Following those docs, I get the same outcome:
```
(p37) PS C:\Repos\screen\yolov5-rt-stack\tools> python .\convert.py
We're using TensorRT: 8.4.1.5 on cuda device: 0.
Loaded saved model from C:\Repos\screen\yolov5\runs\train\exp9\weights\best.pt
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\anchor_utils.py:46: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  anchors = torch.as_tensor(self.anchor_grids, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\anchor_utils.py:47: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\relay\logits_decoder.py:45: TracerWarning: torch.as_tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  strides = torch.as_tensor(self.strides, dtype=torch.float32, device=device).to(dtype=dtype)
C:\ProgramData\Anaconda3\envs\p37\lib\site-packages\yolort\models\box_head.py:337: TracerWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  for head_output, grid, shift, stride in zip(head_outputs, grids, shifts, strides):
```
```
from yolort.runtime.trt_helper import export_tensorrt_engine
import os
import torch
import cv2

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
cuda_visible = "0"
os.environ["CUDA_VISIBLE_DEVICES"] = cuda_visible

assert torch.cuda.is_available()
device = torch.device('cuda')

import tensorrt as trt
print(f"We're using TensorRT: {trt.__version__} on {device} device: {cuda_visible}.")

img_raw = cv2.imread("C:\\Users\\Administrator\\Pictures\\0a1df875-out00900.jpg")

model_path = "C:\\Repos\\screen\\yolov5\\runs\\train\\exp9\\weights\\best.pt"
engine_path = "C:\\best.engine"

batch_size = 1
img_size = 640
size_divisible = 32
fixed_shape = True
score_thresh = 0.80
nms_thresh = 0.45
detections_per_img = 1
precision = "fp16"

export_tensorrt_engine(
    model_path,
    score_thresh=score_thresh,
    nms_thresh=nms_thresh,
    engine_path=engine_path,
    detections_per_img=detections_per_img,
    precision=precision
)
```

**Comment by rlewkowicz** [comment]
This is the only yolov5 c++ tensort project on the internet that actually seems to compile on windows. If this conversion worked, it would be the end to this nightmarish hellscape that is trying to get yolov5, tensorrt, and c++ to work on windows in a native windows project.

I've tried running it as admin etc, it case it was pathing issues. It's odd it exits quietly. I'll dig more at this tomorrow.

**Comment by zhiqwang** [comment]
Did you get the intermediate ONNX models? If the "*.trt.onnx" is generated, you can try use `trtexec` to export the tensorrt plan(engine).

**Comment by rlewkowicz** [comment]
Something ended up being strange with my conda env. I realized it when i went back to use the native ultralytics tool-chain. Same thing, just a quiet exit. 

Just a from scratch fresh env that might help people:
```
# 2. Update conda
conda update -yn base -c defaults conda

# 3. Create virtual environment named 'p37'
conda create -y -n p37 python=3.7 anaconda

# 4. Activate
conda activate p37  # conda deactivate

# 5. Install dependencies
conda install -yc anaconda opencv matplotlib tqdm pillow
conda install -yc conda-forge scikit-image pycocotools protobuf numpy
conda install -yc pytorch pytorch torchvision
pip install onnx
```

**Comment by rlewkowicz** [comment]
Well, not so fast. So I did have to reinstall the whole env to get the ultralytics toolchain to work, but installing yolort is what causes the env to break I believe. 

there's so many moving parts, ymmv. I did a 
```
 pip install yolort --no-deps
```
And this allowed it to install without breaking the env. From there the only missing dep was  onnxruntime, which I've added to the commands above. 

and it works
`Serialize engine success, saved as best.engine`

**Comment by zhiqwang** [comment]
Hi @rlewkowicz , 

I guess that there are some dependencies in following requirements.txt that is not compatible on Windows system, could you open a new ticket and post the error message there so we can check if we can eliminate the use of this dependency?

https://github.com/zhiqwang/yolov5-rt-stack/blob/a9d8a7cb26ca4da6a4b8e7af8a1b17950e07755f/requirements.txt#L13-L31
